name: Update Web Server

on:
  push:
    branches:
      - main  # Adjust this branch name based on your repository's branch setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH into Web Server
        uses: appleboy/ssh-action@v0.16.1
        with:
          host: 31.31.198.57
          username: u2082305
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /www/cicdsite.site/cicd/
            git pull
