name: Update Web Server

on:
  push:
    branches:
      - main  # Adjust this branch name based on your repository's branch setup

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      
    - name: Update data
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd www/cicdsite.site/cicd
          git pull
      
          
          
